### ISSUE TITLE
Audit code for potential improvement in design, readability, safety & performance

### ISSUE THREAD

**Issue by jonancm** [jonancm/rhinochip-os#1]
- [ ] Use C99 integer types (see [Efficient C Tips #1 – Choosing the correct integer size](http://embeddedgurus.com/stack-overflow/2008/06/efficient-c-tips-1-choosing-the-correct-integer-size/))
- [ ] Use [Saks notation](http://www.dansaks.com/articles/1999-02%20const%20T%20vs%20T%20const.pdf) for `const` as suggested in [Efficient C Tips #8 – Use const](http://embeddedgurus.com/stack-overflow/2009/03/efficient-c-tips-8-use-const/)
- [ ] Replace humongous `switch` from function `interpret_cmd` in module [gpcore/shell.c](https://github.com/jonancm/rhinochip-os/blob/88fae3e00c7c7f5cdb5777968582718b17953085/gpcore/shell.c) with jump tables according to this article on [Jump Tables via Function Pointer Arrays in C/C++](http://www.rmbconsulting.us/jump-tables-via-function-pointer-arrays-in-cc)
- [ ] Refactor functions like `set_motor_mode` from [gpcore/controller_status.h](https://github.com/jonancm/rhinochip-os/blob/0142884e2c8dc801ef3e42fa9a41b8bb18c322de/gpcore/controller_status.h) according to [Efficient C Tip #11 – Avoid passing parameters by using more small functions](http://embeddedgurus.com/stack-overflow/2010/02/efficient-c-tip-11-avoid-passing-parameters-by-using-more-small-functions/)
- [ ] Analyze performance if ISRs (see [Minimize Interrupt Service Routine Overhead](http://www.rmbconsulting.us/minimize-interrupt-service-routine-overhead))

More on Efficient C:
- [Efficient C Tips #1 – Choosing the correct integer size](http://embeddedgurus.com/stack-overflow/2008/06/efficient-c-tips-1-choosing-the-correct-integer-size/)
- [Efficient C Tips #2 – Using the optimizer](http://embeddedgurus.com/stack-overflow/2008/07/efficient-c-tips-2-using-the-optimizer/)
- [Efficient C Tips #3 – Avoiding post increment / decrement](http://embeddedgurus.com/stack-overflow/2008/08/efficient-c-tips-3-avoiding-post-increment-decrement/)
- [Efficient C Tips #4 – Use Speed Optimization](http://embeddedgurus.com/stack-overflow/2008/09/efficient-c-tips-4-use-speed-optimization/)
- [Efficient C Tips #5 – Make ‘local’ functions ‘static’](http://embeddedgurus.com/stack-overflow/2008/12/efficient-c-tips-5-make-local-functions-static/)
- [Efficient C Tips #6 – Don’t use the ternary operator](http://embeddedgurus.com/stack-overflow/2009/02/efficient-c-tips-6-dont-use-the-ternary-operator/)
- [Efficient C Tips #7 – Fast loops](http://embeddedgurus.com/stack-overflow/2009/03/efficient-c-tips-7-fast-loops/)
- [Efficient C Tips #8 – Use const](http://embeddedgurus.com/stack-overflow/2009/03/efficient-c-tips-8-use-const/)
- [Efficient C Tips #9 – Use lookup tables](http://embeddedgurus.com/stack-overflow/2009/05/efficient-c-tips-9-use-lookup-tables/)
- [Efficient C Tips #10 – Use unsigned integers](http://embeddedgurus.com/stack-overflow/2009/07/efficient-c-tips-10-use-unsigned-integers/)
- [Efficient C Tip #11 – Avoid passing parameters by using more small functions](http://embeddedgurus.com/stack-overflow/2010/02/efficient-c-tip-11-avoid-passing-parameters-by-using-more-small-functions/)
- [Efficient C Tip #12 – Be wary of switch statements](http://embeddedgurus.com/stack-overflow/2010/04/efficient-c-tip-12-be-wary-of-switch-statements/)
- [Efficient C Tip #13 – use the modulus (%) operator with caution](http://embeddedgurus.com/stack-overflow/2011/02/efficient-c-tip-13-use-the-modulus-operator-with-caution/)
